PATCHES = [
    {"id": "14.13", "display_name": "Patch 14.13", "release_date": "2026-06-12", "is_current": False},
    {"id": "14.14", "display_name": "Patch 14.14", "release_date": "2026-06-26", "is_current": False},
    {"id": "14.15", "display_name": "Patch 14.15", "release_date": "2026-07-10", "is_current": True},
]

COMPOSITIONS = [
    {
        "id": "comp-001",
        "name": "Rebel Fast 8",
        "slug": "rebel-fast-8",
        "playstyle": "Fast 8",
        "difficulty": "Medium",
        "summary": "Stable late-game board that rewards economy management and flexible itemisation.",
        "units": [{"name": "Jinx", "cost": 4, "role": "Carry", "recommended_stars": 2, "priority": 1}],
        "traits": [{"name": "Rebel", "active_tier": "5", "breakpoint_text": "5 Rebels active"}],
        "items": [{"name": "Guinsoo's Rageblade", "category": "Attack Speed", "holder": "Jinx", "priority": 1}],
        "strengths": ["Strong capped board", "Flexible AD item holders"],
        "weaknesses": ["Needs stable economy", "Contested four-cost carries hurt consistency"],
        "timing_notes": ["Push level 8 on 4-2 when healthy", "Stabilise around upgraded four-cost carries"],
        "stats": [{"patch": "14.15", "region": "OC1", "rank_tier": "Diamond+", "games": 18420, "average_placement": 3.72, "top_four_rate": 0.613, "win_rate": 0.176, "pick_rate": 0.089}],
    },
    {
        "id": "comp-002",
        "name": "Academy Reroll",
        "slug": "academy-reroll",
        "playstyle": "Reroll",
        "difficulty": "Easy",
        "summary": "A low-cost reroll line that converts early copies into a dependable top-four board.",
        "units": [{"name": "Ezreal", "cost": 2, "role": "Carry", "recommended_stars": 3, "priority": 1}],
        "traits": [{"name": "Academy", "active_tier": "4", "breakpoint_text": "4 Academies active"}],
        "items": [{"name": "Jeweled Gauntlet", "category": "Ability Power", "holder": "Ezreal", "priority": 1}],
        "strengths": ["Reliable early tempo", "Low gold stabilisation"],
        "weaknesses": ["Caps below five-cost boards", "Needs three-star carry"],
        "timing_notes": ["Slow roll above 50 gold at level 6", "Level after core upgrades"],
        "stats": [{"patch": "14.15", "region": "OC1", "rank_tier": "Diamond+", "games": 15290, "average_placement": 3.89, "top_four_rate": 0.584, "win_rate": 0.149, "pick_rate": 0.074}],
    },
    {
        "id": "comp-003",
        "name": "Enforcer Standard",
        "slug": "enforcer-standard",
        "playstyle": "Standard",
        "difficulty": "Medium",
        "summary": "A balanced level-seven transition board with sturdy frontline and consistent backline damage.",
        "units": [{"name": "Caitlyn", "cost": 3, "role": "Carry", "recommended_stars": 2, "priority": 1}],
        "traits": [{"name": "Enforcer", "active_tier": "4", "breakpoint_text": "4 Enforcers active"}],
        "items": [{"name": "Last Whisper", "category": "Attack Damage", "holder": "Caitlyn", "priority": 1}],
        "strengths": ["Flexible pivot options", "Consistent mid-game"],
        "weaknesses": ["Requires positioning", "Can lose to capped boards"],
        "timing_notes": ["Roll on 3-5 for a stable level 7 board", "Push level 8 after stabilising"],
        "stats": [{"patch": "14.15", "region": "NA1", "rank_tier": "Emerald+", "games": 12960, "average_placement": 4.03, "top_four_rate": 0.542, "win_rate": 0.121, "pick_rate": 0.063}],
    },
    {
        "id": "comp-004",
        "name": "Conqueror Fast 9",
        "slug": "conqueror-fast-9",
        "playstyle": "Fast 9",
        "difficulty": "Hard",
        "summary": "An economy-first cap that uses high-cost units to turn a healthy stage four into a first-place board.",
        "units": [{"name": "Ambessa", "cost": 5, "role": "Carry", "recommended_stars": 2, "priority": 1}],
        "traits": [{"name": "Conqueror", "active_tier": "6", "breakpoint_text": "6 Conquerors active"}],
        "items": [{"name": "Bloodthirster", "category": "Attack Damage", "holder": "Ambessa", "priority": 1}],
        "strengths": ["Very high cap", "Uses legendary units well"],
        "weaknesses": ["Fragile when behind", "Requires strong economy"],
        "timing_notes": ["Preserve health through stage 4", "Level 9 on 5-2 when possible"],
        "stats": [{"patch": "14.15", "region": "EUW1", "rank_tier": "Master+", "games": 6450, "average_placement": 3.61, "top_four_rate": 0.629, "win_rate": 0.201, "pick_rate": 0.031}],
    },
    {
        "id": "comp-005",
        "name": "Bruiser Tempo",
        "slug": "bruiser-tempo",
        "playstyle": "Tempo",
        "difficulty": "Easy",
        "summary": "A health-preserving tempo composition that pressures lobbies before late-game boards come online.",
        "units": [{"name": "Vi", "cost": 3, "role": "Tank", "recommended_stars": 2, "priority": 1}],
        "traits": [{"name": "Bruiser", "active_tier": "6", "breakpoint_text": "6 Bruisers active"}],
        "items": [{"name": "Warmog's Armor", "category": "Health", "holder": "Vi", "priority": 1}],
        "strengths": ["Strong frontline", "Simple itemisation"],
        "weaknesses": ["Limited backline damage", "Falls off at level 9"],
        "timing_notes": ["Level aggressively through stage 3", "Roll to preserve streaks"],
        "stats": [{"patch": "14.14", "region": "OC1", "rank_tier": "Platinum+", "games": 11340, "average_placement": 4.16, "top_four_rate": 0.508, "win_rate": 0.098, "pick_rate": 0.052}],
    },
    {
        "id": "comp-006",
        "name": "Sniper Slow Roll",
        "slug": "sniper-slow-roll",
        "playstyle": "Slow Roll",
        "difficulty": "Hard",
        "summary": "A precise backline reroll composition that rewards scouting and a protected carry setup.",
        "units": [{"name": "Kog'Maw", "cost": 1, "role": "Carry", "recommended_stars": 3, "priority": 1}],
        "traits": [{"name": "Sniper", "active_tier": "4", "breakpoint_text": "4 Snipers active"}],
        "items": [{"name": "Infinity Edge", "category": "Critical Strike", "holder": "Kog'Maw", "priority": 1}],
        "strengths": ["Excellent single-target damage", "Strong with ideal positioning"],
        "weaknesses": ["Vulnerable to divers", "Dependent on three-star units"],
        "timing_notes": ["Slow roll at level 5 for the one-cost carry", "Scout every round before positioning"],
        "stats": [{"patch": "14.13", "region": "KR", "rank_tier": "Diamond+", "games": 7980, "average_placement": 4.28, "top_four_rate": 0.477, "win_rate": 0.084, "pick_rate": 0.039}],
    },
]
